### ISSUE TITLE
Fallo en macOS

### ISSUE THREAD

**Issue by Aimonius** [vulturno/lurte#18]
Hola, al intentar instalar SED de GNU a través de Homebrew me da este error:
`Error: invalid option: --default-names`

**Comment by jorgeatgu** [comment]
Acabo de ver que homebrew desactivo esa opción el mes pasado. Bueno prueba sin ese flag y te debería dejar instalarlo.

`brew install gnu-sed`

**Comment by jorgeatgu** [comment]
Ya he actualizado el README. Y he subido un pequeño cambio para eliminar las comillas dobles.

**Comment by JesusLopTem** [comment]
Todo bien ahora. Agradecido.
